[2022-05-13 17:20:21,875] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-05-11T14:00:15.813135+00:00 [queued]>
[2022-05-13 17:20:21,887] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-05-11T14:00:15.813135+00:00 [queued]>
[2022-05-13 17:20:21,887] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 17:20:21,887] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-13 17:20:21,887] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-13 17:20:21,912] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2022-05-11 14:00:15.813135+00:00
[2022-05-13 17:20:21,916] {standard_task_runner.py:52} INFO - Started process 10351 to run task
[2022-05-13 17:20:21,921] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-05-11T14:00:15.813135+00:00', '--job-id', '49', '--raw', '--subdir', '/usr/local/lib/python3.10/dist-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpwu0ppkn8', '--error-file', '/tmp/tmpvw7o94am']
[2022-05-13 17:20:21,921] {standard_task_runner.py:80} INFO - Job 49: Subtask also_run_this
[2022-05-13 17:20:21,974] {task_command.py:369} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-05-11T14:00:15.813135+00:00 [running]> on host roshan-Latitude-E5440
[2022-05-13 17:20:22,045] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-05-11T14:00:15.813135+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-11T14:00:15.813135+00:00
[2022-05-13 17:20:22,047] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-13 17:20:22,048] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-05-11T14:00:15.813135+00:00 | dag_run=<DagRun example_bash_operator @ 2022-05-11 14:00:15.813135+00:00: manual__2022-05-11T14:00:15.813135+00:00, externally triggered: True>"']
[2022-05-13 17:20:22,057] {subprocess.py:85} INFO - Output:
[2022-05-13 17:20:22,059] {subprocess.py:92} INFO - run_id=manual__2022-05-11T14:00:15.813135+00:00 | dag_run=<DagRun example_bash_operator @ 2022-05-11 14:00:15.813135+00:00: manual__2022-05-11T14:00:15.813135+00:00, externally triggered: True>
[2022-05-13 17:20:22,059] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-13 17:20:22,094] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220511T140015, start_date=20220513T115021, end_date=20220513T115022
[2022-05-13 17:20:22,133] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-13 17:20:22,160] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
